### ISSUE TITLE
Footer margin 

### ISSUE THREAD

**Issue by Horror26** [Horror26/StudyNotion#1]
reduce  the footer  bottom margin (from logo to bottem)
![image](https://github.com/Horror26/StudyNotion/assets/98795410/755fc64f-5a03-4c4f-b9c2-6116e060f98c)

**Comment by om453** [comment]
Hello @Horror26  assign me this issue i can solve this

**Comment by Horror26** [comment]
if you face any issue in local setup do say me 
and you can use npm run start coz its fronted issue
