### ISSUE TITLE
Gap in review slider

### ISSUE THREAD

**Issue by Horror26** [Horror26/StudyNotion#2]
reduce the margin between review slider and footer
![image](https://github.com/Horror26/StudyNotion/assets/98795410/bfca870e-c294-4271-af91-a3d7da98ad68)

**Comment by ChaudaryHammad** [comment]
assign it to me

**Comment by ChaudaryHammad** [comment]
Before:
![image](https://github.com/Horror26/StudyNotion/assets/102407219/d58c3f6a-b28e-4c02-b44c-4ae78cba69e5)
After:
![image](https://github.com/Horror26/StudyNotion/assets/102407219/8fc92237-c289-4bee-b30b-b2fc0e856a65)

I have not configured backend that's way it is not showing reviews.

**Comment by Horror26** [comment]
increase bit gap

**Comment by ChaudaryHammad** [comment]
gap between reviews or gap between footer and reviews section? Because i have decreased it between footer and reviews section.

**Comment by Horror26** [comment]
ohh ok no issues make Pr for this 
![image](https://github.com/Horror26/StudyNotion/assets/98795410/47bab882-4079-4a38-929f-fc3b640b0d8b)
