### ISSUE TITLE
Hover effect for login and signup

### ISSUE THREAD

**Issue by KiranPolaki** [Horror26/StudyNotion#22]
Your web page looks great not gonna lie💥.

But it would be great if the hover effects also work login and signup buttons same like other buttons on the page!

**Comment by Horror26** [comment]
ya of course thanks for noticing it would you like to work on it

**Comment by KiranPolaki** [comment]
yes I will be working on it :)

**Comment by Horror26** [comment]
make pr with base <22-hover-effect-for-login-and-signup>
