### ISSUE TITLE
Adding Scroll To Top Button 

### ISSUE THREAD

**Issue by Ayusht777** [Horror26/StudyNotion#26]
Hey I want to add scroll to top button so user can easily navigate back to top

**Comment by Horror26** [comment]
Ya good idea

**Comment by Ayusht777** [comment]
hi i am getting various error

![image](https://github.com/Horror26/StudyNotion/assets/106388215/b818b015-dd3c-4e00-a8ab-8859eaaed306)

**Comment by Horror26** [comment]
which command you are using for starting server <npm run start>?

**Comment by Ayusht777** [comment]
i used npm install than npm run dev and also removed the .env file

**Comment by Horror26** [comment]
> i used npm install than npm run dev and also removed the .env file 

Add. Env file on root wich is example. Env and use npm run start

**Comment by Ayusht777** [comment]
ok

**Comment by Horror26** [comment]
Do make pr n base branch <26-adding-scroll-to-top-button>

**Comment by Horror26** [comment]
@Ayusht777 use git fetch origiin and then git checkout
