### ISSUE TITLE
Adding transition  to Catalog navbar

### ISSUE THREAD

**Issue by Ayusht777** [Horror26/StudyNotion#27]
![image](https://github.com/Horror26/StudyNotion/assets/106388215/5dcf6c19-09d6-4934-83fd-44835a2cf6e5)

**Comment by Horror26** [comment]
Please Make pr with base branch <27-adding-transition-to-catalog-navbar>

**Comment by Horror26** [comment]
> the catalog section is not working can you tell does it require any api or data

ya of course you have to setup backend which is not possible
so if you can make make dummy data for it

**Comment by Ayusht777** [comment]
ok but i did no back end so can you assigned to anyone else sorry for that

**Comment by Horror26** [comment]
Ya no problem you can take other issues too
