### ISSUE TITLE
Add border to logo

### ISSUE THREAD

**Issue by Horror26** [Horror26/StudyNotion#3]
Add a white border to logo in navbar of 2px
![image](https://github.com/Horror26/StudyNotion/assets/98795410/78adf119-49a5-40f8-91d7-f2330a4e6881)

**Comment by amilpa** [comment]
I'm interested in working on this issue. Could you please assign it to me? I believe I can contribute effectively to its resolution.

**Comment by ChaudaryHammad** [comment]
I can do this assign it to me bro

**Comment by Horror26** [comment]
if you encounter any issue in local setup do say me and you can use npm run start coz its fronted issue

**Comment by ChaudaryHammad** [comment]
Let me know if it's better
![image](https://github.com/Horror26/StudyNotion/assets/102407219/3221fd74-8e15-460c-ad23-43b98b1356a0)

**Comment by Horror26** [comment]
do it bit rounded

**Comment by ChaudaryHammad** [comment]
oky 
![image](https://github.com/Horror26/StudyNotion/assets/102407219/f7a0b65e-fd6f-4a33-b79d-41386a4aeb28)
i have noted some issues with your footer
this looks better
![image](https://github.com/Horror26/StudyNotion/assets/102407219/12c7d537-e783-41a0-8997-db2294ec1ec7)

**Comment by Horror26** [comment]
Looks good

**Comment by Horror26** [comment]
Make an Pr with new branch name (the branch with issue no)

**Comment by ChaudaryHammad** [comment]
i have created a new branch addBorderToLogo and made changes in this branch. Is there any conflict?
