### ISSUE TITLE
Change images

### ISSUE THREAD

**Issue by Horror26** [Horror26/StudyNotion#31]
Change images of about us page add saome realistic images 
you can use ai for that 
![image](https://github.com/Horror26/StudyNotion/assets/98795410/0b6444d8-42c6-40c3-9ad0-0b02be7212b1)

**Comment by Ayusht777** [comment]
lets try it

**Comment by Sujal942** [comment]
Hey i want to contribute in this issue can you please assign it to me under hacktoberfer-2024

**Comment by Horror26** [comment]
please do this before 
git fetch origin
git checkout 31-change-images

**Comment by Sujal942** [comment]
ok Thanks sir
