### ISSUE TITLE
Improving catalog page

### ISSUE THREAD

**Issue by Pree46** [Horror26/StudyNotion#38]
These are the few changes you can include in your catalog page in order to make your website even more attractive and efficient.
⭐Adding images relevant to the content just like uemy, or udacity websites will look much more proper and appropriate in the catalog page. 
⭐Explore full catalog in the home page leads to the Sign up page. The user need not sign up in order to view the catalog. Instead the user can be lead to the catalog page itself.
⭐Most popular and New have the same courses.
⭐New courses should'nt have the frequently bought feature.
⭐The author names can also be a little bit different for each course.(Few courses have the same name - asd aa)
[https://study-notion-frontend-wheat.vercel.app/catalog/blockchain](url)

**Comment by Horror26** [comment]
to view catalog user didn't have to signup

**Comment by Horror26** [comment]
@Pree46 would you like to work on issues you mentioned

**Comment by Pree46** [comment]
Yeah i can work on it and will try to make some changes in the catalog.

**Comment by Horror26** [comment]
but ig you will be facing issues in setting up backend in local machine

**Comment by Pree46** [comment]
i will try. if i face any issues i wil let you know.

**Comment by Pree46** [comment]
yeah im facing quite a lot of issues, hence i have just added the image file and added few images there. You can add those images from your end i guess.

**Comment by shlok-2003** [comment]
assign me this issue
