### ISSUE TITLE
Change video

### ISSUE THREAD

**Issue by Horror26** [Horror26/StudyNotion#5]
change the video and add an better video or animation which can connect to the audience 
![image](https://github.com/Horror26/StudyNotion/assets/98795410/72bd609d-bb8b-4695-9354-fd8b6f1b6532)

**Comment by Pinaka-Pani-18** [comment]
I would like to work on this issue, could you please assign me ?

**Comment by Pinaka-Pani-18** [comment]
Can I add this One ?
https://github.com/Horror26/StudyNotion/assets/102857774/205154d9-5fea-4ce2-8498-a491cde6e8a2

**Comment by Horror26** [comment]
no add something which is eye catching and innovative

**Comment by Pinaka-Pani-18** [comment]
> no add something which is eye catching and innovative

Okay.

**Comment by Pinaka-Pani-18** [comment]
Sorry for the inconvenience, I am unable to work on this issue.

**Comment by Joseph2001-braganza** [comment]
Hello,
Can I work on this Issue.

**Comment by Horror26** [comment]
> Hello, Can I work on this Issue.

ya of course do check above conversation for guidance

**Comment by Joseph2001-braganza** [comment]
Some Suggestions :
1. https://www.pexels.com/video/people-coding-on-computer-6804109/
2. https://www.pexels.com/video/sitting-technology-computer-pc-4709302/
3. https://www.pexels.com/video/a-programmer-working-on-a-laptop-computer-13522186/
4. https://www.pexels.com/video/a-man-typing-on-a-laptop-7989676/
5. https://www.pexels.com/video/man-working-using-the-computer-6963751/

**Comment by Horror26** [comment]
3 is good if possible try some realistic videos from any other website otherwise make pr for adding 3

**Comment by Joseph2001-braganza** [comment]
Yeah I will checkout some more videos and will update you.

**Comment by Joseph2001-braganza** [comment]
I have created a PR just check.
